post/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from django.views.decorators.csrf import requires_csrf_token
from django.shortcuts import reverse
from . import views

app_name = "post"
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('food/', views.new_food, name='new_food'),
    path('food/<int:pk>', views.new_food, name='food'),
    path('food/<int:pk>', views.new_food, name='edit_food'),
    path('foodlist/', login_required(views.FoodListView.as_view(), login_url='/login'), name='food_list'),

    path('meal/', views.meal, name='new_meal'),
    path('meal/<int:pk>', views.meal, name='meal'),
    path('meal/<int:pk>', views.meal, name='edit_meal'),
    path('meallist/', login_required(views.MealListView.as_view(), login_url='/login'),  name='meal_list'),
    path('delete_meal/<int:pk>', views.delete_meal, name='delete_meal'),

    path('weight/', views.weight, name='weight'),

    path('training/', views.training, name='new_training'),
    path('training/<int:pk>', views.training, name='training'),
    path('training/<int:pk>', views.training, name='edit_training'),
    path('training_list/', login_required(views.TrainingListView.as_view(), login_url='/login'), name='training_list'),

    path('exercise/', views.exercise, name='new_exercise'),
    path('exercise/<int:pk>', views.exercise, name='exercise'),
    path('exercise/<int:pk>', views.exercise, name='edit_exercise'),
    path('exercise_list/', login_required(views.ExerciseListView.as_view(), login_url='/login'), name='exercise_list'),
    path('delete_exercise/<int:pk>', views.delete_exercise, name='delete_exercise'),

    path('stats/', views.stats_view, name='stats'),
    path('stats/weight_graph', views.generate_weight_graph, name='weight_graph'),
    path('stats/calorie_graph', views.generate_calorie_graph, name='calorie_graph'),
    path('stats/nutrition_graph', views.generate_nutrition_graph, name='nutrition_graph'),
]

postsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('post.urls'), name="homepage"),
    path('admin/', admin.site.urls),
]

post/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class FoodType(models.Model):
    food_type_name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.food_type_name


def validate_value(value):
    if value < 0:
        raise ValidationError(_('%(value)s is negative'), params={'value': value}, )


class BodyStatistics(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    weight = models.FloatField(default=70)
    date = models.DateField(default=timezone.now)

    # Date should be unique (for each user)

    def __str__(self):
        return "Weight: " + str(self.weight) + " " + str(self.date)


class Food(models.Model):
    food_name = models.CharField(max_length=200)
    food_type = models.ForeignKey(FoodType, on_delete=models.CASCADE)
    energy = models.IntegerField(default=0, validators=[validate_value])
    fat = models.FloatField(default=0.0, validators=[validate_value])
    saturated = models.FloatField(default=0.0, validators=[validate_value])
    carb = models.FloatField(default=0.0, validators=[validate_value])
    sugar = models.FloatField(default=0.0, validators=[validate_value])
    protein = models.FloatField(default=0.0, validators=[validate_value])
    salt = models.FloatField(default=0.0, validators=[validate_value])
    def_weight = models.FloatField(default=100, validators=[validate_value])

    popularity = models.IntegerField(default=0)
    notes = models.CharField(max_length=2048, null=True, blank=True)

    def __str__(self):
        return self.food_name


class Meal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    food = models.ForeignKey(Food, on_delete=models.PROTECT)
    date = models.DateTimeField(default=timezone.now)
    weight = models.FloatField(default=0, validators=[validate_value])

    def __str__(self):
        return self.food.food_name + " " + str(self.date)


class Training(models.Model):
    name = models.CharField(max_length=200)
    calories_per_hour = models.FloatField(default=0)

    def __str__(self):
        return self.name


class Exercise(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    training = models.ForeignKey(Training, on_delete=models.SET_NULL, null=True)
    minutes = models.IntegerField(default=60)
    date = models.DateTimeField(default=timezone.now)
    burned_calories_custom = models.FloatField(default=None, null=True, blank=True)

    def __str__(self):
        return self.training.name + str(self.date)


def now_plus_one_day():
    return timezone.now() + datetime.timedelta(days=1)


class Schedule(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date_start = models.DateTimeField(default=timezone.now)
    date_end = models.DateTimeField(default=now_plus_one_day)
    message = models.CharField(max_length=1024)

    def __str__(self):
        return self.name


# For informing/highlighting elements when the user is close to reaching limit
# Also can be used when creating statistics
class Limits(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time_span = models.PositiveIntegerField(default=1)

    # FIXME setting blank and null to True allows us to save empty fields in admin view
    # but it does not work with TextField and CharField
    energy = models.FloatField(default=None, null=True, blank=True)
    fat = models.FloatField(default=None, null=True, blank=True)
    saturated = models.FloatField(default=None, null=True, blank=True)
    carb = models.FloatField(default=None, null=True, blank=True)
    sugar = models.FloatField(default=None, null=True, blank=True)
    salt = models.FloatField(default=None, null=True, blank=True)
    weight = models.FloatField(default=None, null=True, blank=True)

    def __str__(self):
        s = self.user.username + " (time_span: " + str(self.time_span) + ") - "
        for k in ["energy", "fat", "saturated", "carb", "sugar", "salt", "weight"]:
            if self.__getattribute__(k) is not None:
                s += k + ":" + str(self.__getattribute__(k)) + " "
        return s

    class Meta:
        unique_together = (('user', 'time_span'),)


class Goals(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    deadline = models.DateField()
    weight = models.FloatField(default=70)

    # TODO add support for other goals (calorie intake?, sugars?)
    # maybe create a new table for the goalTypes

    def __str__(self):
        s = self.user.username + " (deadline: " + str(self.deadline) + ") - "
        if self.weight is not None:
            s += "Weight:" + str(self.weight)
        return s

post/views.py
import io
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import timedelta, datetime
from django.core.exceptions import PermissionDenied
from django.db.models import Count
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.http import HttpRequest, HttpResponseRedirect, Http404, FileResponse
from django.utils import timezone, dateformat, dateparse

from .models import Meal, Food, FoodType, BodyStatistics, Training, Exercise, Goals, Limits

matplotlib.use('agg')


def login_view(request):
    if request.method == "GET":
        return render(request, 'post/login.html')
    elif request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        print(request.POST['csrfmiddlewaretoken'])
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(request.GET['next'] if request.GET.get('next') else reverse("post:index"))
        else:
            render(request, 'post/login.html', {'error': "Niepoprawne dane."})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("post:login"))


def create_stats(user, date):
    today = date.replace(hour=0, minute=0, second=0, microsecond=0)
    meals = Meal.objects.filter(user=user, date__gte=today, date__lt=today + timedelta(days=1))
    stats = {
        "fat": 0,
        "saturated": 0,
        "carb": 0,
        "sugar": 0,
        "salt": 0,
        "weight": 0,
    }
    for m in meals:
        stats['fat'] += m.food.fat * m.weight / 100.0
        stats['saturated'] += m.food.saturated * m.weight / 100.0
        stats['carb'] += m.food.carb * m.weight / 100.0
        stats['sugar'] += m.food.sugar * m.weight / 100.0
        stats['salt'] += m.food.salt * m.weight / 100.0
        stats['weight'] += m.weight

    stats['fat'] = round(stats['fat'], 1)
    stats['saturated'] = round(stats['saturated'], 1)
    stats['carb'] = round(stats['carb'], 1)
    stats['sugar'] = round(stats['sugar'], 1)
    stats['salt'] = round(stats['salt'], 1)
    stats['weight'] = round(stats['weight'], 1)
    return stats


def get_meals(user, date):
    today = date.replace(hour=0, minute=0, second=0, microsecond=0)
    tomorrow = today + timedelta(days=1)
    meals = Meal.objects.filter(user=user, date__gte=today, date__lt=tomorrow)
    return meals


def get_weight(user, date):
    try:
        bs = BodyStatistics.objects.get(user=user, date=date)
    except (KeyError, BodyStatistics.DoesNotExist):
        return None
    else:
        return bs.weight


def get_excercises(user, date):
    today = date.replace(hour=0, minute=0, second=0, microsecond=0)
    tomorrow = today + timedelta(days=1)
    return Exercise.objects.filter(user=user, date__gte=today, date__lt=tomorrow)


def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("post:login"))

    current_day = request.GET.get('date')
    if current_day is None:
        current_day = timezone.now()
    else:
        current_day = datetime.strptime(current_day, "%Y-%m-%d")
        

    # Add calories attribute
    kcal_sum = 0
    meals = get_meals(request.user, current_day)
    for m in meals:
        m.calories = m.weight * m.food.energy / 100
        kcal_sum += m.calories
    stats = create_stats(request.user, current_day)
    weight = get_weight(request.user, current_day)
    favourite_foods = Meal.objects.filter(user=request.user).values('food').annotate(total=Count('food')).order_by(
        '-total')[
                      :5]
    for r in favourite_foods:
        r['food'] = Food.objects.get(pk=r['food'])
    exercises = get_excercises(request.user, current_day)


    return render(request, "post/index.html",
                  {'meals': meals,
                   'sum': round(kcal_sum),
                   'fill': range(10 - len(meals)),
                   'stats': stats,
                   'weight': weight,
                   'popular_foods': Food.objects.filter(popularity__gte=1).order_by('-popularity')[:5],
                   'favourite_foods': favourite_foods,
                   'exercises': exercises,
                   'exercises_energy_sum': sum(
                       [e.minutes * e.training.calories_per_hour / 60 for e in exercises]),
                   'exercises_time_sum': sum(
                       [e.minutes for e in exercises]),
                   'limits': Limits.objects.filter(user=request.user, time_span=1).first(),
                   'goals': Goals.objects.filter(user=request.user, deadline__gte=current_day.date()).first(),
                   'current_day': current_day,
                   'previous_day': current_day + timedelta(days=-1),
                   'next_day': current_day + timedelta(days=1),
                   })


def weight(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("post:login"))
    if request.method == "POST":
        date = timezone.now().date()
        weight_ = float(request.POST["weight"])
        user = request.user
        bs = None
        try:
            bs = BodyStatistics.objects.get(user=user, date=date)
        except (KeyError, BodyStatistics.DoesNotExist):
            pass
        if bs is None:
            BodyStatistics(user=user, date=date, weight=weight_).save()
        else:
            bs.weight = weight_
            bs.save()
        return HttpResponseRedirect(request.GET['next'] if request.GET.get('next') else reverse('post:index'))
    else:
        raise Http404()


def new_food(request: HttpRequest, pk=None):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("post:login"))
    if request.method == "POST":
        if pk is None:
            f = Food()
        else:
            f = get_object_or_404(Food, pk=pk)
        f.food_name = request.POST['fname']
        f.food_type = get_object_or_404(FoodType, pk=request.POST['ftype'])
        f.energy = request.POST['fenergy']
        f.fat = request.POST['ffat']
        f.saturated = request.POST['fsaturated']
        f.carb = request.POST['fcarb']
        f.sugar = request.POST['fsugar']
        f.protein = request.POST['fprotein']
        f.salt = request.POST['fsalt']
        f.def_weight = request.POST['fdef_weight']
        f.save()
        return HttpResponseRedirect(request.GET['next'] if request.GET.get('next') else reverse("post:food_list"))
    if request.method == "GET":
        if pk is None:
            return render(request, "post/food.html",
                          {'food_type': FoodType.objects.all()
                           })
        else:
            f = get_object_or_404(Food, pk=pk)
            return render(request, "post/food.html",
                          {'food_type': FoodType.objects.all(),
                           'food': f,
                           })


def meal(request: HttpRequest, pk=None):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("post:login"))
    if request.method == "POST":
        if pk is None:
            m = Meal()
        else:
            m = get_object_or_404(Meal, user=request.user, pk=pk)
        m.user = request.user
        m.food = get_object_or_404(Food, pk=request.POST['mfood'])
        m.date = request.POST['mdate']
        if request.POST['weightchoice'] == '1':
            m.weight = m.food.def_weight * int(request.POST['mportions'])
        else:
            m.weight = request.POST['mweight']
        m.save()
        m.food.popularity += 1
        m.food.save()
        return HttpResponseRedirect(request.GET['next'] if request.GET.get('next') else reverse("post:meal_list"))
    if request.method == "GET":
        food_list = Food.objects.all()
        if pk is None:
            selected_food = None
            if request.GET.get('food'):
                selected_food = get_object_or_404(Food, pk=request.GET.get('food'))
            return render(request, "post/meal.html",
                          {"food_list": food_list,
                           'selected_food': selected_food,
                           'date': dateformat.format(timezone.now(), 'Y-m-d'),
                           })
        else:
            m = get_object_or_404(Meal, user=request.user, pk=pk)
            return render(request, "post/meal.html",
                          {"meal": m,
                           "food_list": food_list})


def delete_meal(request, pk):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("post:login"))
    m = get_object_or_404(Meal, user=request.user, pk=pk)
    if request.user != m.user:
        raise PermissionDenied("Nie twój posiłek.")
    m.delete()
    return HttpResponseRedirect(request.GET['next'] if request.GET.get('next') else reverse('post:index'))


class IndexView(generic.DetailView):
    template_name = "post/index.html"

    def get_queryset(self):
        pass


class FoodListView(generic.ListView):
    template_name = "post/food_list.html"
    context_object_name = 'food_list'
    paginate_by = 20
    login_required = True

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['food_type'] = FoodType.objects.all()
        return context

    def get_queryset(self):
        query = self.request.GET.get('q')
        order = self.request.GET.get('order')
        type_filter = self.request.GET.get('type_filter')

        foods = Food.objects.all()

        if query:
            foods = Food.objects.filter(food_name__icontains=query)
        if order:
            foods = foods.order_by(order)

post/templates/post/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link href="{% static 'post/style.css' %}" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" type="image/png" href="{% static 'post/favicon.ico' %}"/>

    <title>{% block title %}Title{% endblock %}</title>
</head>
<body>
{% include "post/header.html" %}
{% include "post/navbar.html" %}

{% block body %}{% endblock %}

</body>
</html>

post/templates/post/exercise.html
{% extends "post/base.html" %}
{% block title %}Post - Ćwiczenie{% endblock %}
{% block body %}

{% if exercise %}
<form action="{% url 'post:exercise' exercise.id %}{% if request.GET.next %}?next={{request.GET.next}}{%endif%}" method="post">
{% else %}
<form action="{% url 'post:new_exercise' %}{% if request.GET.next %}?next={{request.GET.next}}{%endif%}" method="post">
{% endif %}
    {% csrf_token %}
    <label for="training">Trening</label>
    <select id="training" name="training">
        {%for training in training_list %}
            {% if selected_training %}
                <option value="{{training.id}}" {% if selected_training.id == training.id %} selected {%endif%}>{{training.name}}</option>
            {% else %}
                <option value="{{training.id}}" {% if training.id == exercise.training.id %} selected {%endif%}>{{training.name}}</option>
            {% endif %}
        {%endfor%}
    </select>
    <label for="date">Data</label>
    {% if exercise %}
    <input type="date" id="date" name='date' value="{{exercise.date|date:'Y-m-d'}}">
    {% else %}
    <input type="date" id="date" name='date' value="{% now 'Y-m-d'%}">
    {% endif %}
    <label for="time">Czas</label>
    <input type="number" id="time" name="time" value="{% if exercise %}{{exercise.minutes}}{%else%}60{%endif%}">
    <input type="submit">
    <input type="reset">
    {% if exercise %}
    <input type="button" value="Delete" onclick="location.href='{% url 'post:delete_exercise' exercise.id %}{% if request.GET.next %}?next={{request.GET.next}}{%endif%}'"/>
    {% endif %}
    <input type="button" value="Back" style="float: right" onclick="history.back()">
</form>
{% endblock %}

post/templates/post/exercise_list.html
{% extends "post/base.html" %}
{% block title %}Lista Moich Ćwiczeń{% endblock %}
{% block body%}

<a href="{% url 'post:new_exercise'%}?next={{request.path}}">Nowe Ćwiczenie...</a>
    {% if exercise_list %}
        <table class="generictable">
            <tr>
                <th>ID</th>
                <th>Nazwa</th>
                <th>Data</th>
                <th>Długość Treningu</th>
                <th>Spalanych kalorii</th>
            </tr>
            {% for exercise in exercise_list %}
            <tr>
                <td><a href="{% url 'post:exercise' exercise.id%}?next={{request.path}}">{{exercise.id}}</a></td>
                <td>{{exercise.training.name}}</td>
                <td>{{exercise.date|date:"SHORT_DATE_FORMAT"}}</td>
                <td>{{exercise.minutes}}</td>
                <td>{% widthratio exercise.minutes 60 exercise.training.calories_per_hour%}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>Nie znaleziono żadnych treningów.</p>
    {% endif %}

{% endblock %}

post/templates/post/favourite_foods.html
{% if favourite_foods %}
<div align="center">
    <h3>Twoje Ulubione</h3>
    <table>
        {% for f in favourite_foods %}
            <tr>
                <td><a href="{% url 'post:new_meal' %}?food={{f.food.id}}&next={{request.path}}">[+]</a></td>
                <td>{{f.food.food_name}}</td>
                <td>{{f.total}}</td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endif %}

post/templates/post/food.html
{% extends "post/base.html" %}
{% block title %}Danie{% endblock %}
{% block body%}
    <style>
        form {
            border-radius: 10px;
            background-color: #f2f2f2;
            padding: 20px;
        }

        input[type=text],
        input[type=number],
        select {
            width: 100%;
        }

        input[type=submit],
        input[type=reset] {}

    </style>


{% if food %}
<form action="{% url 'post:edit_food' food.id %}" method="post">
    {% else %}
    <form action="{% url 'post:new_food' %}" method="post">
        {% endif %}
        {% csrf_token %}
        <label for="fname">Nazwa</label>
        <input type="text" id="fname" name="fname" value="{{food.food_name}}">
        <label for="ftype">Rodzaj</label>
        <select id="ftype" name="ftype">
            {%for type in food_type %}
            <option value="{{type.id}}" {% if type.id == food.food_type.id %} selected {% endif %}>{{type.food_type_name}}</option>
            {%endfor%}
        </select>
        <label for="fenergy">Energia</label>
        <input type="number" id="fenergy" name="fenergy" value="{{food.energy}}" min="0">
        <label for="ffat">Tłuszcz</label>
        <input type="number" id="ffat" name="ffat" value="{{food.fat}}" min="0" step="0.1">
        <label for="fsaturated">Kwasy tłuszczowe nasycone</label>
        <input type="number" id="fsaturated" name="fsaturated" value="{{food.saturated}}" min="0" step="0.1">
        <label for="fcarb">Węglowodany</label>
        <input type="number" id="fcarb" name="fcarb" value="{{food.carb}}" min="0" step="0.1">
        <label for="fsugar">Cukry</label>
        <input type="number" id="fsugar" name="fsugar" value="{{food.sugar}}" min="0" step="0.1">
        <label for="fprotein">Białko</label>
        <input type="number" id="fprotein" name="fprotein" value="{{food.protein}}" min="0" step="0.1">
        <label for="fsalt">Sól</label>
        <input type="number" id="fsalt" name="fsalt" value="{{food.salt}}" min="0" step="0.01">
        <label for="fdef_weight">Waga jednej porcji</label>
        <input type="number" id="fdef_weight" name="fdef_weight" value="{{food.def_weight}}" min="0" step="0.1">
        <input type="submit">
        <input type="reset">
        <input type="button" value="Back" style="float: right" onclick="history.back()">
    </form>

{% endblock %}

post/templates/post/food_list.html
{% extends "post/base.html" %}
{% block title %}Lista Dań{% endblock %}
{% block body%}

<form method="get" action="" id="searchform">
    <input type="text" id="searchbox" name="q" value="{{request.GET.q}}" placeholder="Szukaj..."/>
    <select name="order">
        <option value="-popularity">Popularność</option>
        <option value="-food_name">Nazwa (Malej.)</option>
        <option value="food_name">Nazwa (Rosn.)</option>
        <option value="-energy">Energia (Malej.)</option>
        <option value="energy">Energia (Rosn.)</option>
    </select>
    
    <select name="type_filter">
        <option value="-1">Wszystkie</option>
        {%for type in food_type %}
            <option value="{{type.id}}" {% if type.id == request.GET.type_filter|add:"0" %} selected {% endif %}>{{type.food_type_name}}</option>
        {%endfor%}
    </select>
    <input type="submit"/>
</form>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
         <span class="prev" style="float:left">
            <a href="?{%if request.GET.q %}q={{request.GET.q}}&{%endif%}page=1">&laquo; first</a>
            <a href="?{%if request.GET.q %}q={{request.GET.q}}&{%endif%}page={{ page_obj.previous_page_number }}">previous</a>
         </span>
        {% endif %}
        <span class="current" style="float:left">
            <form method="get" action="?">
                Page <input type="number" name="page" value="{{ page_obj.number }}" style="width: 4em"> of {{ page_obj.paginator.num_pages }}.
            </form>
        </span>
        {% if page_obj.has_next %}
         <span class="next" style="float:left">
            <a href="?{%if request.GET.q %}q={{request.GET.q}}&{%endif%}page={{ page_obj.next_page_number }}">next</a>
            <a href="?{%if request.GET.q %}q={{request.GET.q}}&{%endif%}page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
         </span>
        {% endif %}
    </span>
</div>

{%if food_list%}
<table class="mealtable">
    <tr>
        <th>Nazwa</th>
        <th>Rodzaj</th>
        <th>Energia</th>
        <th>Tłuszcz</th>
        <th>w tym nasycone</th>
        <th>Węglowodany</th>
        <th>w tym cukry</th>
        <th>Białko</th>
        <th>Sól</th>
        <th>Waga 1 porcji</th>
        <th>Popularność</th>
        <th>Posiłek</th>
    </tr>
    {% for food in food_list %}
    <tr>
        <td><a href="{% url 'post:food' food.id %}">{{food.food_name}}</a></td>
        <td>{{food.food_type.food_type_name}}</td>
        <td>{{food.energy}}</td>
        <td>{{food.fat}}</td>
        <td>{{food.saturated}}</td>
        <td>{{food.carb}}</td>
        <td>{{food.sugar}}</td>
        <td>{{food.protein}}</td>
        <td>{{food.salt}}</td>
        <td>{{food.def_weight}}</td>
        <td>{{food.popularity}}</td>
        <td><a href="{% url 'post:new_meal'%}?food={{food.id}}">[+]</a></td>
    </tr>
    {% endfor %}
</table>
{% else %}
<p>Nie ma dań do wyświetlenia!</p>
{% endif %}

{% endblock %}

post/templates/post/meal_list.html
{% extends "post/base.html" %}
{% block title %}Lista Posiłków{% endblock %}
{% block body%}

<a href="{% url 'post:new_meal' %}">Nowy Posiłek...</a>
{%if meal_list%}
<table class="mealtable">
    <tr>
        <th>ID</th>
        <th>Danie</th>
        <th>Data</th>
        <th>Godzina</th>
        <th>Waga</th>
        <th>Kalorie</th>
    </tr>
    {% for meal in meal_list %}
    <tr>
        <td>{{meal.id}}</td>
        <td><a href="{% url 'post:meal' meal.id %}">{{meal.food.food_name}}</a></td>
        <td>{{meal.date|date:"d M Y"}}</td>
        <td>{{meal.date|date:"H:i"}}</td>
        <td>{{meal.weight}}</td>
        <td>{% widthratio meal.weight 100 meal.food.energy %}</td>
    </tr>

    {% endfor %}
</table>
{% else %}
<p>Nie ma dań do wyświetlenia!</p>
{% endif %}
{% endblock %}

post/templates/post/popular_foods.html
{% if popular_foods %}
<div align="center">
    <h3>Popularne</h3>
    <table>
        {% for f in popular_foods %}
            <tr>
                <td><a href="{% url 'post:new_meal' %}?food={{f.id}}&next={{request.path}}">[+]</a></td>
                <td>{{f.food_name}}</td>
                <td>{{f.popularity}}</td>
            </tr>
        {% endfor %}
    </table>
</div>
{% endif %}

post/templates/post/stats.html
{% extends "post/base.html" %}
{% block title %}Statystyki dla {{start_date}} - {{end_date}}{% endblock %}
{% block body %}

<form method="get">
    <input type="date" name="start_date" value="{{start_date|date:'Y-m-d'}}">
    <input type="date" name="end_date" value="{{end_date|date:'Y-m-d'}}">
    <input type="submit">
</form>

<img src="{% url 'post:weight_graph'%}?start_date={{start_date|date:'Y-m-d'}}&end_date={{end_date|date:'Y-m-d'}}"/>
<img src="{% url 'post:calorie_graph'%}?start_date={{start_date|date:'Y-m-d'}}&end_date={{end_date|date:'Y-m-d'}}"/>
<img src="{% url 'post:nutrition_graph'%}?start_date={{start_date|date:'Y-m-d'}}&end_date={{end_date|date:'Y-m-d'}}"/>

{% endblock %}

post/templates/post/training_list.html
{% extends "post/base.html" %}
{% block title %}Lista Treningów{% endblock %}
{% block body%}
<a href="{% url 'post:new_training'%}">Nowy Trening...</a>
    {% if training_list %}
        <table class="generictable">
            <tr>
                <th>Nazwa</th>
                <th>Spalanych kalorii na godzinę</th>
                <th>Nowe Ćwiczenie</th>
            </tr>
            {% for training in training_list %}
            <tr>
                <td><a href="{% url 'post:training' training.id%}">{{training.name}}</a></td>
                <td>{{training.calories_per_hour}}</td>
                <td><a href="{% url 'post:new_exercise'%}?t_id={{training.id}}">[+]</a></td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>Nie znaleziono żadnych treningów.</p>
    {% endif %}

{% endblock %}